version: "3"

services:
  life-support-service:
    image: "soa-team-e/life-support-service"
    restart: always
    command: npm run start
    ports:
      - 4304:4204
    environment:
      - APP_PORT=4204
      - APP_NAME=life-support-service
      - MONGODB_HOST=mongo_db_life_support
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=life-support-db
      - SWAGGERUI_PATH=doc/life-support
      - SWAGGERUI_TITLE=Life Support Micro-Service
      - SWAGGERUI_DESCRIPTION=Destiné à la surveillance des conditions des systèmes de support des modules habités
      - MODULE_LIFE_SERVICE_URL_WITH_PORT=module-life-service:4203
    depends_on:
      - mongo_db_life_support
    networks:
      - soa-team-e-network
  mongo_db_life_support:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - 27021:27017
    networks:
      - soa-team-e-network
networks:
  soa-team-e-network:
    driver: bridge
